runtime: nodejs18
service: ms-auth
env: standard
instance_class: F1
env_variables:
  NODE_ENV: production
  BASE_URL: https://ms-auth-dot-lustrous-bonito-409316.rj.r.appspot.com
  PORT: 8080
  VERSION: v1
  API_KEY: 5a3f8ef464f8f63a89c4c9fdb7082bd52d9e353730cf6eb76a8cb66f0ffbb46c
  # JWT CONFIG
  JWT_SECRET: 8a796db321b94bdc8b14398a2653d492d293725796de69a03f52ab89e28b91f0cd7343ab932dd90722fe2073341bbe9ea751ba3944cfbe11f1d6a352be5b4590
  TOKEN_EXPIRES_IN: 1h
  REFRESH_TOKEN_EXPIRES_IN: 1d
  # DB CONFIG
  DB_SOCKET_PATH: /cloudsql/lustrous-bonito-409316:southamerica-east1:test-gcp-instance
  DB_USER: root
  DB_PASSWORD: lpkkn/9y6/vC3??s
  DB_SECURITY_NAME: db_auth_prod
  # OAUTH2 CONFIG
  ## GOOGLE CREDENTIALS: GO TO https://console.cloud.google.com/ FOR DETAILS
  GOOGLE_CLIENT_ID: 180238564829-27vglotl6e70efa7niiq5pq5ekh4hqpp.apps.googleusercontent.com
  GOOGLE_CLIENT_SECRET: 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
  GOOGLE_CALLBACK_URL: https://ms-auth-dot-lustrous-bonito-409316.rj.r.appspot.com/v1/api/auth/google/redirect
  ## FACEBOOK CREDENTIALS: GO TO https://developers.facebook.com/ FOR DETAILS
  FACEBOOK_APP_ID: 1089079888901065
  FACEBOOK_APP_SECRET: c2e9260bd941ad4df5bee101df5d7890
  FACEBOOK_CALLBACK_URL: https://ms-auth-dot-lustrous-bonito-409316.rj.r.appspot.com/v1/api/auth/facebook/redirect
  ## GITHUB CREDENTIALS: GO TO https://github.com/settings/developers FOR DETAILS
  GITHUB_APP_ID: c2be81f5dda07f7fbae5
  GITHUB_APP_SECRET: 3d0c675f0c9a32ad843febfe3d9fdf977f90b815
  GITHUB_CALLBACK_URL: https://ms-auth-dot-lustrous-bonito-409316.rj.r.appspot.com/v1/api/auth/github/redirect
  ## TWITTER CREDENTIALS: GO TO https://developer.twitter.com/en FOR DETAILS
  TWITTER_APP_ID: Q9Z4O1WXymddSmnLbJqz3Z1ok
  TWITTER_APP_SECRET: iHpPHCzEnwzfhhBcPSbIsmJwv6TNDFlWX3lScQfYh40M5K3wWt
  TWITTER_CALLBACK_URL: https://ms-auth-dot-lustrous-bonito-409316.rj.r.appspot.com/v1/api/auth/twitter/redirect

  FRONTEND_CALLBACK_URL: https://lustrous-bonito-409316.rj.r.appspot.com/authentication/oauth-redirect
